# Generated by Django 5.0.4 on 2024-04-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_buyer_alter_cart_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='buyer',
        ),
    ]
